name: setlog Code Quality and Build
on:
  pull_request:
    branches:
      - main
jobs:
  setlog-check_pyproject_toml_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensure we fetch the main branch for comparison
      - name: Extract current version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(grep -Po '(?<=version = ")[^"]*' ./apps/setlog/pyproject.toml)
          echo "Current version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_ENV"
      - name: Check if pyproject.toml has changed
        run: |
          git fetch origin main
          if git diff origin/main --exit-code -- ./apps/setlog/pyproject.toml; then
            echo "The version in pyproject.toml must be incremented. Current version: $VERSION"
            exit 1
          else
            echo "Changes detected in pyproject.toml. Proceeding..."
          fi
  setlog-check_changes_md_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensure we fetch the main branch for comparison
      - name: Check if CHANGES.md has changed
        run: |
          git fetch origin main
          if git diff origin/main --exit-code -- ./apps/setlog/CHANGES.md; then
            echo "A changelog entry must be added to CHANGES.md."
            exit 1
          else
            echo "Changes detected in CHANGES.md. Proceeding..."
          fi
  setlog-lock_file:
    runs-on: ubuntu-latest
    needs: [ setlog-check_pyproject_toml_changes, setlog-check_changes_md_changes ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: cd ./apps/setlog/; uv lock --locked
  setlog-ruff_check:
    runs-on: ubuntu-latest
    needs: [setlog-lock_file]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv run ruff check ./apps/setlog/
  setlog-ruff_format:
    runs-on: ubuntu-latest
    needs: [lock_file]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv run ruff format ./apps/setlog/
  setlog-unit_tests:
    runs-on: ubuntu-latest
    needs: [ lock_file ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv run pytest ./apps/setlog/tests/pebble/unit_tests -v --durations=0 --cov=src --cov-report=xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  setlog-build:
    runs-on: [ ubuntu-latest ]
    needs: [ setlog-ruff_check, setlog-ruff_format, setlog-unit_tests]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv build
